// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fetiyniznqrppgodting.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZldGl5bml6bnFycHBnb2R0aW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3ODQ1NTcsImV4cCI6MjA1NDM2MDU1N30.o2VOBILZ06Fy-k2HdNyQoGr1hqh32NYHnq2QkpqE0MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);